### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by frieza213** [vadim-ahmerov/Commander#1]
Hey there maybe you should add a haptic feedback when trying to switch application it would be a very nice addition in my opinion and make the app more fun to interact with

**Comment by vadim-ahmerov** [comment]
Hey there
That's a great idea – adding haptic feedback for switching applications indeed makes the app more interactive. I've implemented this feature, and the updated version 1.13 is now in review. It should be available for download in a couple of days. Thank you for your suggestion!
